# Generated by Django 3.2.25 on 2025-04-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('composition_al', models.FloatField(default=0, verbose_name='Al元素含量')),
                ('composition_c', models.FloatField(default=0, verbose_name='C元素含量')),
                ('composition_co', models.FloatField(default=0, verbose_name='Co元素含量')),
                ('composition_cr', models.FloatField(default=0, verbose_name='Cr元素含量')),
                ('composition_cu', models.FloatField(default=0, verbose_name='Cu元素含量')),
                ('composition_fe', models.FloatField(default=0, verbose_name='Fe元素含量')),
                ('composition_hf', models.FloatField(default=0, verbose_name='Hf元素含量')),
                ('composition_mg', models.FloatField(default=0, verbose_name='Mg元素含量')),
                ('composition_mn', models.FloatField(default=0, verbose_name='Mn元素含量')),
                ('composition_mo', models.FloatField(default=0, verbose_name='Mo元素含量')),
                ('composition_n', models.FloatField(default=0, verbose_name='N元素含量')),
                ('composition_nb', models.FloatField(default=0, verbose_name='Nb元素含量')),
                ('composition_ni', models.FloatField(default=0, verbose_name='Ni元素含量')),
                ('composition_sc', models.FloatField(default=0, verbose_name='Sc元素含量')),
                ('composition_si', models.FloatField(default=0, verbose_name='Si元素含量')),
                ('composition_sn', models.FloatField(default=0, verbose_name='Sn元素含量')),
                ('composition_ta', models.FloatField(default=0, verbose_name='Ta元素含量')),
                ('composition_ti', models.FloatField(default=0, verbose_name='Ti元素含量')),
                ('composition_v', models.FloatField(default=0, verbose_name='V元素含量')),
                ('composition_w', models.FloatField(default=0, verbose_name='W元素含量')),
                ('composition_y', models.FloatField(default=0, verbose_name='Y元素含量')),
                ('composition_zn', models.FloatField(default=0, verbose_name='Zn元素含量')),
                ('composition_zr', models.FloatField(default=0, verbose_name='Zr元素含量')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='RoomTempProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardness', models.FloatField(blank=True, null=True, verbose_name='硬度(HV)')),
                ('tensile_strength', models.FloatField(blank=True, null=True, verbose_name='抗拉强度(MPa)')),
                ('yield_strength', models.FloatField(blank=True, null=True, verbose_name='屈服强度(MPa)')),
                ('elongation', models.FloatField(blank=True, null=True, verbose_name='延伸率(%)')),
                ('elastic_modulus', models.FloatField(blank=True, null=True, verbose_name='弹性模量(GPa)')),
                ('test_temperature', models.FloatField(default=25, verbose_name='测试温度(℃)')),
                ('test_method', models.CharField(max_length=100, verbose_name='测试方法')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_temp_property', to='materials.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '室温力学性能',
                'verbose_name_plural': '室温力学性能',
                'db_table': 'room_temp_properties',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='制备方法')),
                ('temperature', models.FloatField(verbose_name='热处理温度(℃)')),
                ('duration', models.FloatField(verbose_name='热处理时间(h)')),
                ('cooling_method', models.CharField(max_length=50, verbose_name='冷却方式')),
                ('details', models.TextField(blank=True, null=True, verbose_name='工艺细节')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='materials.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '工艺',
                'verbose_name_plural': '工艺',
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'db_table': 'material_properties',
            },
        ),
    ]
